<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="format-detection" content="telephone=no,email=no">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="full-screen" content="yes">
     <title>canvas watermark demo</title>
    <meta name="description" content="canvas demo watermark">
    <meta name="keywords" content="canvas">
    <!-- inject:css -->
    <link href="css/semantic.min.css" rel="stylesheet">
    <!-- endinject -->
</head>
<body>   